import type { DiskusiPost, CurrentUser } from '@/types/Forum-Page.types';

/** Mock "logged in" user — di implementasi asli ini akan datang dari auth/session. */
export const currentUser: CurrentUser = {
  id: 'me',
  nama: 'Kamu',
  inisial: 'KM',
};

export const seedPosts: DiskusiPost[] = [
  {
    id: 'post-1',
    authorId: 'me',
    authorNama: 'Kamu',
    judul: 'Bagaimana cara normalisasi database sampai 3NF untuk tugas Basis Data?',
    isi: 'Aku masih bingung bedain 2NF sama 3NF, khususnya di kasus tabel Transaksi yang punya banyak foreign key. Ada yang bisa jelasin pakai contoh dari tugas kita minggu ini?',
    kategori: 'tugas',
    tags: ['basis-data', 'normalisasi'],
    createdAt: '2026-07-21T09:12:00',
    votes: 14,
    userVote: 0,
    views: 132,
    jawabanTerbaikId: 'jwb-1',
    jawaban: [
      {
        id: 'jwb-1',
        postId: 'post-1',
        authorId: 'u-dimas',
        authorNama: 'Dimas Aditya',
        isi: '3NF itu syaratnya semua kolom non-key harus bergantung penuh ke primary key DAN tidak boleh ada dependensi transitif (kolom non-key bergantung ke kolom non-key lain). Di tabel Transaksi kita, kolom "nama_barang" sebaiknya dipindah ke tabel Barang karena dia bergantung ke barang_id, bukan langsung ke transaksi_id.',
        createdAt: '2026-07-21T10:03:00',
        votes: 9,
        userVote: 0,
        balasan: [
          {
            id: 'bls-1',
            postId: 'post-1',
            jawabanId: 'jwb-1',
            authorId: 'me',
            authorNama: 'Kamu',
            isi: 'Ooh jadi intinya pisahin yang bisa berdiri sendiri jadi tabel baru ya. Makasih Dimas!',
            createdAt: '2026-07-21T10:20:00',
          },
        ],
      },
      {
        id: 'jwb-2',
        postId: 'post-1',
        authorId: 'u-indah',
        authorNama: 'Indah Sari',
        isi: 'Tambahan, coba gambar dulu ER diagram-nya sebelum normalisasi, biasanya ketahuan mana yang redundant.',
        createdAt: '2026-07-21T11:45:00',
        votes: 4,
        userVote: 0,
        balasan: [],
      },
    ],
  },
  {
    id: 'post-2',
    authorId: 'u-farhan',
    authorNama: 'Farhan Maulana',
    judul: 'Cari partner buat proyek akhir: aplikasi manajemen kelas',
    isi: 'Aku lagi bikin proyek akhir semester, aplikasi manajemen kelas berbasis web pakai React + Node. Butuh 1-2 orang buat bagian backend. Siapa yang tertarik?',
    kategori: 'proyek',
    tags: ['react', 'nodejs', 'cari-tim'],
    createdAt: '2026-07-20T14:30:00',
    votes: 21,
    userVote: 1,
    views: 210,
    jawaban: [
      {
        id: 'jwb-3',
        postId: 'post-2',
        authorId: 'me',
        authorNama: 'Kamu',
        isi: 'Aku tertarik! Kebetulan lagi belajar Express & PostgreSQL. Boleh chat aku di grup ya.',
        createdAt: '2026-07-20T15:10:00',
        votes: 6,
        userVote: 0,
        balasan: [
          {
            id: 'bls-2',
            postId: 'post-2',
            jawabanId: 'jwb-3',
            authorId: 'u-farhan',
            authorNama: 'Farhan Maulana',
            isi: 'Mantap, nanti aku add ke grup diskusi proyeknya ya!',
            createdAt: '2026-07-20T15:40:00',
          },
        ],
      },
    ],
  },
  {
    id: 'post-3',
    authorId: 'u-gita',
    authorNama: 'Gita Lestari',
    judul: 'Error "Cannot read property of undefined" pas fetch API di tugas Praktikum Jaringan',
    isi: 'Aku coba fetch data dari API dummy tapi selalu error itu di console. Kodenya sudah aku ikutin sesuai modul praktikum. Ada yang pernah ngalamin?',
    kategori: 'tugas',
    tags: ['javascript', 'api', 'debugging'],
    createdAt: '2026-07-22T08:05:00',
    votes: 5,
    userVote: 0,
    views: 47,
    jawaban: [],
  },
];
